//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renls
    {
        public int codeR { get; set; }
        public int idCustemers { get; set; }
        public int idCars { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string goalRenl { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Custemers Custemers { get; set; }
    }
}
